Repository Punit-Choudhary/Python-beginner-scripts, pull requests merged in 2022-10, with the labels that each got.

#32 Updated area_of_triangle.py
  Math/area _of_triangle.py
  Math/area_of_triangle.py
Labels: hacktoberfest-accepted

#42 Added Symbol Pattern 126
  Patterns/Symbol Patterns/code/Symbol_Pattern_126.py/README.md
  Patterns/Symbol Patterns/code/Symbol_Pattern_126.py/symbol_pattern_126.py
Labels: hacktoberfest-accepted

#45 Added scripts to create pyramid pattern 1
  Patterns/Pyramid Patterns/Code/main.py
  Patterns/Pyramid Patterns/Code/readme.md
Labels: hacktoberfest-accepted

#47 Fibonacci code added
  Math/n_fibonacci_numbers.py
Labels: hacktoberfest-accepted

#56 Numeric Pattern 100
  Patterns/Numeric Patterns/Code/Numeric_Pattern_100/numeric_pattern100.py
  Patterns/Numeric Patterns/Code/Numeric_Pattern_100/readme.md
Labels: hacktoberfest-accepted

#59 Numeric Pattern 101
  Patterns/Numeric Patterns/Code/Numeric_Pattern_101/numeric_pattern101.py
  Patterns/Numeric Patterns/Code/Numeric_Pattern_101/readme.md
Labels: hacktoberfest-accepted

#60 Added Python code to calculate factorial
  Math/n_factorial.py
Labels: hacktoberfest-accepted

#76 Create bubblesort_visualizer.py
  Projects/bubblesort_visualizer.py
Labels: hacktoberfest-accepted

#100 Added 3D Cube Visualizer
  Projects/Visualize3D_Cube/README.md
  Projects/Visualize3D_Cube/ice.py
  Projects/Visualize3D_Cube/requirements.txt
  Projects/Visualize3D_Cube/visualizer.py
Labels: hacktoberfest-accepted

#106 Matrix Text Generator
  Projects/Matrix_Text_Gen/README.md
  Projects/Matrix_Text_Gen/main.py
  Projects/Matrix_Text_Gen/requirements.txt
Labels: hacktoberfest-accepted

#120 Adding SENDING_MAILS_WITH_ATTACHMENT project
  Projects/SENDING_MAILS_WITH_ATTACHMENT/README.md
  Projects/SENDING_MAILS_WITH_ATTACHMENT/credentials.json
  Projects/SENDING_MAILS_WITH_ATTACHMENT/main.py
  Projects/SENDING_MAILS_WITH_ATTACHMENT/requirements.txt
Labels: hacktoberfest-accepted

#149 Create circumference_of_hemisphere.py
  Math/circumference_of_hemisphere.py
Labels: hacktoberfest-accepted

#178 Alpahbetic pattern 101
  Patterns/Alphabetic_Patterns/Code/alphabetic_pattern_101/README.md
  Patterns/Alphabetic_Patterns/Code/alphabetic_pattern_101/pattern101.py
Labels: hacktoberfest-accepted

#189 Added code for volume of square pyramid
  Math/volume_of_square_pyramid.py
Labels: hacktoberfest-accepted

#194 Added code for pyramid pattern 32
  Patterns/Pyramid_Patterns/Code/pyramid_pattern_32/README.md
  Patterns/Pyramid_Patterns/Code/pyramid_pattern_32/pyramid_pattern_32.py
Labels: hacktoberfest-accepted

#222 Add symbol pattern 117
  Patterns/Symbol_Patterns/code/Symbol_Pattern_117/README.md
  Patterns/Symbol_Patterns/code/Symbol_Pattern_117/symbol_pattern_117.py
Labels: hacktoberfest-accepted, Pattern

#227 Symbol Pattern 115
  Patterns/Symbol_Patterns/code/Symbol_Pattern_115/README.md
  Patterns/Symbol_Patterns/code/Symbol_Pattern_115/symbol_pattern_115.py
Labels: hacktoberfest-accepted, Pattern

#218 Created BlackJack Card Game
  Projects/BlackJack Game/README.md
  Projects/BlackJack Game/blackjack.py
Labels: hacktoberfest-accepted, Project

#231 Surface area of Cuboid
  Math/surface_area_of_rectangle.py
Labels: hacktoberfest-accepted, Math

#241 Alphabetic_pattern11
  Patterns/Alphabetic_Patterns/Code/alphabetic_pattern11/alphabetic_pattern11.md
  Patterns/Alphabetic_Patterns/Code/alphabetic_pattern11/pattern11.py
Labels: hacktoberfest-accepted, Pattern
